
CREATE USER 
'Uclientes'@'localhost' 
IDENTIFIED  BY 'Contra1$';
GRANT USAGE ON *.* TO 'Uclientes'@'localhost';

ALTER USER 'Uclientes'@'localhost' 
REQUIRE NONE 
WITH MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `clientes`.* 
TO 'Uclientes'@'localhost';
FLUSH PRIVILEGES;